name: Update Decompilations

on:
  push:
    branches:
      - main
  schedule:
    - '0 0 * * *'

jobs:
  decompile:
    runs-on: 'ubuntu-20.04'
    env:
      ONLY_INCLUDE_STABLE_VERSIONS: true

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Deno
        uses: denoland/setup-deno@v1.0.0
        with:
          deno-version: 'canary'

      - name: Run Decompilation Script
        run: deno run -A sourcecraft.ts
