name: Update Decompilations

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  decompile:
    runs-on: 'ubuntu-20.04'
    env:
      ONLY_INCLUDE_STABLE_VERSIONS: true

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Git User
        uses: fregante/setup-git-user@v1

      - name: Setup JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Set up Deno
        uses: denoland/setup-deno@v1.0.0
        with:
          deno-version: 'canary'

      - name: Run Decompilation Script
        run: deno run -A sourcecraft.ts
